language: php

php:
  - 5.6
  - 5.4
  - 5.5
  - hhvm

env:
  - LARAVEL_VERSION="4.0.*" TESTBENCH_VERSION="2.0.*"
  - LARAVEL_VERSION="4.1.*" TESTBENCH_VERSION="2.1.*"
  - LARAVEL_VERSION="4.2.*" TESTBENCH_VERSION="2.1.*"

before_script:
  - composer self-update
  - composer require orchestra/testbench:"$TESTBENCH_VERSION" --dev
  - composer require illuminate/support:"$LARAVEL_VERSION" --dev
  - composer install --prefer-source --no-interaction --dev

script: phpunit -d memory_limit=1024M

matrix:
  fast_finish: true